### ISSUE TITLE
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### ISSUE THREAD

**Issue by dannycrief** [pirple/Data-Mining-With-Python#1]
For the Python 3 it gives an error

`sns.boxplot(X)` 

it returns:

![image](https://user-images.githubusercontent.com/37116770/112722887-8a756780-8f14-11eb-99bb-3a92654f7c91.png)

**Comment by dannycrief** [comment]
For pyhon3:

`sns.boxplot(data=X)`

**Comment by markfilan** [comment]
[Python](http://net-informations.com/python/default.htm) Pandas follows the numpy convention of raising an error when you try to convert something to a bool. This happens in a if or when using the boolean operations, and, or, or not. It is not clear what the result of.

example

`5 == pd.Series([12,2,5,10])`

The result you get is a Series of booleans, equal in size to the pd.Series in the right hand side of the expression. So, you get an error. The problem here is that you are comparing a pd.Series with a value, so you'll have multiple True and multiple False values, as in the case above. This of course is ambiguous, since the condition is neither True or False. You need to further aggregate the result so that a single boolean value results from the operation. For that you'll have to use either any or all depending on whether you want at least one (any) or all values to satisfy the condition.

```
(5 == pd.Series([12,2,5,10])).all()
# False
```

or

```
(5 == pd.Series([12,2,5,10])).any()
# True
```
